name: Update Items

on:
  workflow_dispatch

jobs:
  update-items:
    permissions: 
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Protoc Go plugin
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '19'

      - name: Checkout
        uses: actions/checkout@v2.3.1
          
      - name: Test
        run: make test
          
      - name: Delete Old DB
        run: rm assets/db_inputs/wowhead_item_tooltips.csv
          
      - name: Update DB
        run: go run ./tools/database/gen_db -outDir=assets -gen=wowhead-items
          
      - name: Make Items
        run: make items
        
      - name: Set Date
        id: date
        run: |
          echo "builddate=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            assets/db_inputs/wowhead_item_tooltips.csv
            assets/database/db.bin
            assets/database/db.json
          branch: update_item_db
          delete-branch: true
          commit-message: 'Update Item DB at ${{ steps.date.outputs.builddate}}'
          title: 'Update Item DB at ${{ steps.date.outputs.builddate}}'
          body: |
            Update Item DB at ${{ steps.date.outputs.builddate}}
